name: Build
on:
  schedule:
    - cron:  '0 5 * * 1'
  push:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/dellelce/gcc11-base

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Mkit gcc11
        run: docker build -t $IMAGE .
      - name: Add tag & push
        run: docker push $IMAGE
